config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :bookmarks
  end
  root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :author, presence:true
  has_many :bookmarks, dependent: :destroy
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :page_num, presence: true
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :prepare_book

  def show

  end

  def index

  end

  def new
    @bookmarks = @book.bookmarks.new
  end

  def create
    @bookmark = @book.bookmarks.new(get_params)
    if @bookmark.save
      redirect_to book_path(@book), method: :get
    else
      # byebug
      render :new
    end
  end

  def edit
    @bookmarks = Bookmark.find(params[:id])
  end

  def update
    @bookmarks = Bookmark.find(params[:id])
    if @bookmarks.update(get_params)
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to book_path
  end

  private

  def get_params
    params.require(:bookmark).permit(:page_num, :description)
  end


  def prepare_book
    @book = Book.find(params[:book_id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @bookmarks = @book.bookmarks.new
  end

  def index
    @books = Book.all
  end

  def new
    @books = Book.new
  end

  def create
    @books = Book.new(get_params)
    if @books.save
      redirect_to books_path
    else
      # byebug
      render :new
    end
  end

  def edit
    @books = Book.find(params[:id])
  end

  def update
    @books = Book.find(params[:id])
    if @books.update(get_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def get_params
    params.require(:book).permit(:name, :author, :read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/bookmarks/new.html.erb
<div class="book-form">
  <h1>Create Bookmark</h1>

  <%= simple_form_for @book.bookmarks.build, url: book_bookmarks_path(@book), html: {class: 'form-horizontal'}, method: :post  do |f| %>

    <div class="form-group">
      <%= f.input :page_num, placeholder: 'Bookmark page number', error: 'page is mandatory, please specify!', class: 'form-control'  %>
    </div>

    <div class="form-group">
      <p><%= f.input :description, placeholder: 'Enter description', class: 'form-control' %></p>
    </div>

    <p><%= f.button :submit, class:'btn btn-outline-primary' %></p>

  <% end %>

  <%= link_to 'Book List', books_path %>
</div>

app/views/books/edit.html.erb
<div class="book-form">
  <h1>Edit Book Details</h1>

  <%= simple_form_for(@books, html: {class: 'form-horizontal'}) do |f| %>

    <div class="form-group">
      <%= f.input :name, placeholder: 'Book title', error: 'Book title is mandatory, please specify!', class: 'form-control'  %>
    </div>

    <div class="form-group">
      <p><%= f.input :author, placeholder: 'Name of author', error: 'Author is mandatory, please specify!', class: 'form-control' %></p>
    </div>
      <div class="form-check">
      <p><%= f.input :read, as: :boolean %></p>
    </div>
    <p><%= f.button :submit, class:'btn btn-outline-primary' %></p>

  <% end %>

  <%= link_to 'Book List', books_path %>
</div>

app/views/books/index.html.erb
<div class="d-flex flex-column">
  <div class="container-fluid">
    <div class="header-hero fixed-top">
      <div class="container header-container">
        <h1 class='display-3'>My Reading List</h1>
      </div>
    </div>
  </div>

  <div class="float-left fixed-top">
    <%= link_to image_tag("notebook.svg", :border => 0, :alt => '', :title => '', :class => 'dock-item'), new_book_path %>
  </div>

  <div class="table-hero">
    <table class='table table-striped table-bordered table-hover table-responsive table-inverse'>
      <thead class='thead-default thead-inverse'>
        <tr>
          <th>#</th>
          <th>Title</th>
          <th>Author</th>
          <th>Read</th>
          <th colspan="3" class="options-header">Options</th>
        </tr>
      </thead>

      <tbody>
        <% index = 0 %>
        <% @books.each do |book| %>
        <% index += 1 %>
        <tr>
          <td><%= index %></td>
          <td><%= book.name %></td>
          <td><%= book.author %></td>
          <td>
            <% if book.read %>
              <p class="badge badge-success">Read</p>
            <% else %>
              <p class="badge badge-dark">Not Read</p>
            <% end %>
          </td>
          <td><%= link_to 'Show ', book_path(book), method: :get %> </td>
          <td><%= link_to 'Edit', edit_book_path(book), method: :get %> </td>
          <td><%= link_to 'Delete', book_path(book), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>




</div>

app/views/books/new.html.erb
<div class="book-form">
  <h1>Create Book</h1>

  <%= simple_form_for(@books, html: {class: 'form-horizontal'}) do |f| %>

    <div class="form-group">
      <%= f.input :name, placeholder: 'Book title', error: 'Book title is mandatory, please specify!', class: 'form-control'  %>
    </div>

    <div class="form-group">
      <p><%= f.input :author, placeholder: 'Name of author', error: 'Author is mandatory, please specify!', class: 'form-control' %></p>
    </div>
      <div class="form-check">
      <p><%= f.input :read, as: :boolean %></p>
    </div>
    <p><%= f.button :submit, class:'btn btn-outline-primary' %></p>

  <% end %>

  <%= link_to 'Book List', books_path %>
</div>

app/views/books/show.html.erb
<!-- <h1>Book</h1> -->

<!-- <ul>
  <li>
    <h2>Title</h2>
    <p><%= @book.name %></p>
  </li>
  <li>
    <h2>Author</h2>
    <p><%= @book.author %></p>
  </li>
  <li>
    <h2>Read</h2>
      <% if @book.read %>
        <p>Book Read!</p>
      <% else %>
        <p>Book Not Read :(</p>
      <% end %>
  </li>
</ul>

<%= link_to 'Back to Book List', books_path %> -->


<div class="card text-center">
  <div class="card-header">
    Book
  </div>
  <div class="card-body">
    <h4 class="card-title">Title: <%= @book.name %></h4>
    <p class="card-text">Author: <%= @book.author %></p>
    <%= link_to 'Back to Book List', books_path, class: "btn btn-primary" %>
  </div>
  <div class="card-footer text-muted">
    Last updated: <%= @book.updated_at %>
  </div>
</div>


<%= link_to image_tag("notebook.svg", :border => 0, :alt => '', :title => '', :class => 'dock-item'), new_book_bookmark_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>My Reading List</title>
  <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Raleway" rel="stylesheet"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>